services:
  backend:
   build: ./Backend
   container_name: backendmedium
   ports:
    - "3000:3000"
   env_file:
    - ./Backend/.env
   restart: unless-stopped

  frontend:
    build: ./Frontend
    container_name: frontendmedium
    ports:
      - "5173:5173"
    depends_on:
      - backend
    env_file:
      - ./Frontend/.env
    restart: unless-stopped